services:
  tts-service:
    image: austinleo/tts-adapter:v2
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config.yaml:/app/config.yaml
      