services:
  tts-service:
    image: austinleo/tts-adapter:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      